interface ArticleContentInterface {
    alt_capa: string;
    alt_imagem_1: string;
    alt_imagem_2: string;
    alt_imagem_3: string;
    alt_imagem_4: string;
    alt_imagem_5: string;
    alt_imagem_6: string;
    alt_imagem_7: string;
    alt_imagem_8: string;
    alt_imagem_9: string;
    alt_imagem_10: string;
    assinatura: string;
    created_at: string;
    fonte_capa: string;
    fonte_imagem_1: string;
    fonte_imagem_2: string;
    fonte_imagem_3: string;
    fonte_imagem_4: string;
    fonte_imagem_5: string;
    fonte_imagem_6: string;
    fonte_imagem_7: string;
    fonte_imagem_8: string;
    fonte_imagem_9: string;
    fonte_imagem_10: string;
    id: string;
    imagem_1: string;
    imagem_2: string;
    imagem_3: string;
    imagem_4: string;
    imagem_5: string;
    imagem_6: string;
    imagem_7: string;
    imagem_8: string;
    imagem_9: string;
    imagem_10: string;
    imagem_capa: string;
    rota: string;
    slug: string;
    subtitulo: string;
    tag: string;
    texto: string;
    titulo: string;
    trailer: string;
    updated_at: string;
}

export default ArticleContentInterface;