name: React build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy dist folder to temporary location
      run: cp -r dist ../dist-temp

    - name: Switch to build branch and clean up
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b build
        rm -rf *  # Remove existing files to avoid conflicts

    - name: Move files to build branch root
      run: |
        cp -r ../dist-temp/* .  # Copy from the temporary location to root
        rm -rf ../dist-temp      # Remove the temporary folder
        git add .
        git commit -m "Build output for deployment"
        git push origin build --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
